-- Fix match_requests table to make potential_match_id optional
-- The potential_match_id is generated by the matching service and doesn't exist in potential_matches table

-- Drop the foreign key constraint
ALTER TABLE match_requests DROP CONSTRAINT IF EXISTS match_requests_potential_match_id_fkey;

-- Change the data type from UUID to TEXT to accept generated string IDs
ALTER TABLE match_requests ALTER COLUMN potential_match_id TYPE TEXT;

-- Make potential_match_id nullable since it's generated by the service
ALTER TABLE match_requests ALTER COLUMN potential_match_id DROP NOT NULL;

-- Add a comment explaining the change
COMMENT ON COLUMN match_requests.potential_match_id IS 'Generated ID from matching service (not a foreign key to potential_matches table)';
